import { StyleSheet } from 'react-native';
import CONFIG from './_CONFIG';

export default comicsStyle = StyleSheet.create({
  cover: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 240,
    backgroundColor: '#000',
  },
  coverButtonContainer: {
    position: 'absolute',
    top: 100,
    right: 0,
    left: 0,
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  mastcontainer: {
    position: 'relative',
    marginTop: 150,
    marginBottom: 20,
    flex: 1,
    alignItems: 'stretch',
    alignSelf: 'stretch',
    flexDirection: 'column',
    marginLeft: 20,
    marginRight: 20,
    backgroundColor: 'pink',
  },
  headShadow: {
    position: 'absolute',
    top: 0,
    right: 0,
    left: 0,
    height: 110,
    marginTop: 150,
    marginLeft: 20,
    marginRight: 20,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: {
      width: 1,
      height: 0,
    },
    shadowOpacity: 0.6,
  },
  headShadowMask: {
    position: 'absolute',
    top: 0,
    right: 0,
    left: 0,
    height: 300,
    marginTop: 150,
    marginLeft: 20,
    marginRight: 20,
    backgroundColor: '#fff',
  },
  mastcontent: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: '#fff',
  },
  head: {
    marginTop: 12,
    marginRight: 20,
    marginLeft: 20,
  },
  title: {
    marginTop: 8,
    color: CONFIG.titleColor,
    fontFamily: CONFIG.fontFamilyAlt,
    fontSize: 26,
    fontWeight: '300',
    lineHeight: 30,
  },
  released: {
    marginBottom: 14,
    color: CONFIG.textColor,
    fontFamily: CONFIG.fontFamilyAlt,
    fontSize: 16,
    fontWeight: '300',
  },
  body: {
    marginTop: 20,
    marginRight: 20,
    marginLeft: 20,
  },
  bodyText: {
    color: CONFIG.textColor,
    fontFamily: CONFIG.fontFamily,
    fontSize: 16,
    fontWeight: '300',
    lineHeight: 26,
  },
  meta: {
    marginTop: 30,
    marginRight: 20,
    marginLeft: 20,
  },
  metaText: {
    marginBottom: 4,
    color: CONFIG.grayColor,
    fontFamily: CONFIG.fontFamilyAlt,
    fontSize: 16,
    // fontStyle: 'italic',
    fontWeight: '300',
  }
});
